import React from "react";

const Head = () => {
  return (
    <>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta content="Generated by create next app" name="description" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
};

export default Head;
